services:
  - type: web
    name: trainewia
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./public